sudo: required
services:
    - docker

before_install:
    - docker build -t manikantavasupalli/docker-react -f Dockerfile.dev .   

script:
    - docker run  manikantavasupalli/docker-react npm run test -- --coverage
