sudo: required
services:
    - docker

before_install:
    - docker build -t manikantavasupalli/docker-react -f Dockerfile.dev .   

script:
    - docker run  manikantavasupalli/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-ebs-react"
    env: "DockerEbsReact-env-1"
    bucket_name: "elasticbeanstalk-ap-south-1-773237655473"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:  $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
